### ISSUE TITLE
Not able to use Row() widget

### ISSUE THREAD

**Issue by kunalsaraf** [adamlofts/mysql1_dart#7] opened 2019-04-07 15:43 UTC
When I import 'package:mysql1/mysql1.dart' package, I am unable to use Row. It says Row is defined in 'package:flutter/src/widgets/basic.dart' as well as 'package:mysql1/mysql1.dart'.
So I have to import the former package explicitly.

**Comment by adamlofts** [comment] 2019-04-18 14:17
Yeah, this is a known issue. Probably Row should be renamed to something else.

**Comment by adamlofts** [comment] 2020-04-10 09:43
Duplicate of #10

**Closed by adamlofts** 2020-04-10 09:43 UTC
