### ISSUE TITLE
Connection to mysql8.0 failed

### ISSUE THREAD

**Issue by disburden** [adamlofts/mysql1_dart#5] opened 2019-02-15 02:51 UTC
Error message:
MySQL Client Error: Authentication plugin not supported: caching_sha2_password

I have already modified the authentication method on the database side.
*************************** 1. row ***************************
                 user: root
                 host: %
               plugin: mysql_native_password
authentication_string: *C1926D

**Comment by adamlofts** [comment] 2019-12-26 11:16
Duplicate of #15

**Closed by adamlofts** 2019-12-26 11:16 UTC
