### ISSUE TITLE
BUG : Row widget conflict with your mysql1

### ISSUE THREAD

**Issue by prohorizon** [adamlofts/mysql1_dart#38] opened 2020-03-13 10:05 UTC
I used your mysql1 to get a connection  `

      Future<Results> connectToDB() async {
       try {
           connection = (connection == null
            ? await MySqlConnection.connect(connection_settings)
            : connection);
 
      results = await connection.query(
          'select company_logoDB from location where cityDB=? & category_id= order by id',
          [name, category_id]);

      results.forEach((element) {  //element param is a database Row 
        city_row_column = element.toList();
        company_logo = city_row_column[0];
      });

      print('connected');
    } on HttpException catch (err) {
      var message = err.message;
      print(message);
    } finally {
      print('Do Something');
    }
    return results;
    }`

Now on the application I have a Row widget:

               `Container(
                  alignment: Alignment.center,
                  padding: EdgeInsets.all(2.0),
                  color: Colors.white,
                  height: 70.0,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Expanded(
                        flex: 1,
                        child: FittedBox(
                ....`

the Row widget is highlited with Red ..when I put cursor on it I get this :

'Row' isn't a function.  Try correcting the name to match an existing function, or define a method or function named 'Row'. Open documentation
The name 'Row' is defined in the libraries 'package:flutter/src/widgets/basic.dart (via package:flutter/widgets.dart)' and 'package:mysql1/src/results/row.dart (via package:mysql1/mysql1.dart)'.  Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

Flutter platform and your API using same name Row though for different perspective ...

 can use Stack but I prefer Row...I need a solution kindly ...I

**Comment by roipeker** [comment] 2020-03-13 15:35
Just import the package and give it an access name.

```
import 'package:mysql1/mysql1.dart' as mysql;
// ....
await mysql.MySqlConnection.connect(connection_settings)
// ....
```

**Comment by prohorizon** [comment] 2020-03-13 16:03
> Just import the package and give it an access name.
> 
> ```
> import 'package:mysql1/mysql1.dart' as mysql;
> // ....
> await mysql.MySqlConnection.connect(connection_settings)
> // ....
> ```

roipeker :  Applying your way worked for the Row widget  in the stateless class , BUT now the MYSQL1 class properties(used to create a connection) went Red:

MySqlConnection connection; 
Results results;
ConnectionSettings conn_settings

Anyway I replaced the Row with ListView :)

**Comment by adamlofts** [comment] 2020-04-10 09:43
Duplicate of #10

**Closed by adamlofts** 2020-04-10 09:43 UTC
